# Build and test VulkanMod Extra for every push and PR
# Ensures compatibility with VulkanMod and Minecraft 1.21.1
# Provides early detection of build issues and regressions

name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java: [ 21 ]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
        
      - name: Setup Java JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
          
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
        
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: false
          
      - name: Build VulkanMod Extra
        run: ./gradlew build
        
      - name: Run checkstyle
        run: ./gradlew checkstyle
        continue-on-error: true
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: VulkanMod-Extra-${{ github.sha }}
          path: build/libs/*.jar
          
      - name: Upload build reports on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build-reports-${{ github.sha }}
          path: build/reports/