name: Issue Management

on:
  issues:
    types: [opened, labeled, unlabeled]
  issue_comment:
    types: [created]

jobs:
  triage-new-issue:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    
    steps:
      - name: Welcome new contributors
        uses: actions/github-script@v7
        with:
          script: |
            // Check if this is the user's first issue
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              creator: context.payload.issue.user.login,
              state: 'all'
            });
            
            if (issues.length === 1) {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `👋 Welcome to VulkanMod Extra! Thanks for your first contribution.
                
                **For faster support:**
                - 🔍 Make sure you've provided all requested information in the template
                - 📋 Check if VulkanMod itself works correctly without VulkanMod Extra
                - 🔧 Try with only VulkanMod + VulkanMod Extra (no other mods) to isolate issues
                - 📖 Check our [Wiki](https://github.com/${context.repo.owner}/${context.repo.repo}/wiki) for common solutions
                
                A maintainer will review your issue soon!`
              });
            }
            
      - name: Auto-label based on issue content
        uses: actions/github-script@v7
        with:
          script: |
            const issueBody = context.payload.issue.body || '';
            const issueTitle = context.payload.issue.title.toLowerCase();
            const labels = [];
            
            // Auto-label based on template selection and content
            if (issueBody.includes('Animation Issues')) labels.push('animations');
            if (issueBody.includes('Particle Issues')) labels.push('particles');
            if (issueBody.includes('GUI/Settings Issues')) labels.push('gui');
            if (issueBody.includes('Performance Issues')) labels.push('performance');
            if (issueBody.includes('HUD/Overlay Issues')) labels.push('hud');
            if (issueBody.includes('Rendering Issues')) labels.push('rendering');
            if (issueBody.includes('Configuration Issues')) labels.push('config');
            if (issueBody.includes('Compatibility Issues')) labels.push('compatibility');
            if (issueBody.includes('Crash/Fatal Error')) labels.push('crash');
            
            // Title-based labeling
            if (issueTitle.includes('crash')) labels.push('crash');
            if (issueTitle.includes('fps') || issueTitle.includes('performance')) labels.push('performance');
            if (issueTitle.includes('animation')) labels.push('animations');
            if (issueTitle.includes('particle')) labels.push('particles');
            if (issueTitle.includes('config') || issueTitle.includes('setting')) labels.push('config');
            
            // Priority detection
            if (issueTitle.includes('critical') || issueTitle.includes('urgent') || issueBody.includes('Critical -')) {
              labels.push('priority-high');
            }
            
            // Add labels if any were found
            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: labels
              });
            }

  close-resolved-issues:
    if: github.event.action == 'created' && contains(github.event.comment.body, '/close')
    runs-on: ubuntu-latest
    
    steps:
      - name: Close issue with resolution comment
        uses: actions/github-script@v7
        with:
          script: |
            // Only allow maintainers to use /close command
            const { data: collaborators } = await github.rest.repos.listCollaborators({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            const isCollaborator = collaborators.some(collaborator => 
              collaborator.login === context.payload.comment.user.login
            );
            
            if (isCollaborator) {
              await github.rest.issues.update({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'closed'
              });
              
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '✅ This issue has been resolved and closed. If you continue to experience problems, please open a new issue with updated information.'
              });
            }

  stale-issue-management:
    if: github.event.action == 'labeled' && github.event.label.name == 'needs-info'
    runs-on: ubuntu-latest
    
    steps:
      - name: Request additional information
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `ℹ️ **Additional Information Needed**
              
              This issue has been labeled as needing more information. To help us resolve your issue:
              
              🔍 **Please provide:**
              - Complete system information (OS, Java version, GPU, drivers)
              - Full VulkanMod Extra configuration (\`.minecraft/config/vulkanmod-extra-options.json\`)
              - Complete mod list or test with minimal setup
              - Detailed reproduction steps
              - Relevant log files (\`.minecraft/logs/latest.log\`)
              
              ⏰ **Timeline:** Issues without sufficient information may be automatically closed after 7 days of inactivity.
              
              📝 **Tip:** You can edit your original issue to add missing information instead of commenting.`
            });

  performance-issue-helper:
    if: github.event.action == 'opened' && contains(github.event.issue.labels.*.name, 'performance')
    runs-on: ubuntu-latest
    
    steps:
      - name: Provide performance troubleshooting guide
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Performance Issue Detected**
              
              Thanks for reporting a performance issue! Here are some quick troubleshooting steps:
              
              ## 🔧 Quick Fixes to Try:
              1. **Disable all animations/particles temporarily** to isolate the cause
              2. **Check VulkanMod settings** - some combinations can impact performance
              3. **Test without other mods** to rule out mod conflicts
              4. **Update GPU drivers** to the latest version
              
              ## 📊 Performance Testing:
              - Test with F3 debug screen open to monitor FPS
              - Compare performance with VulkanMod Extra disabled
              - Note specific areas/actions where FPS drops occur
              
              ## 🎯 VulkanMod Extra Settings That Can Help:
              - **Animations**: Disable specific heavy animations (water, lava, fire)
              - **Particles**: Disable particle-heavy effects  
              - **Fast Random**: Enable for better performance
              - **Light Updates**: Disable if experiencing chunk loading stutters
              
              If none of these help, please provide detailed performance measurements as requested in the template!`
            });

  compatibility-issue-helper:
    if: github.event.action == 'opened' && contains(github.event.issue.labels.*.name, 'compatibility')
    runs-on: ubuntu-latest
    
    steps:
      - name: Provide compatibility troubleshooting guide
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🔗 **Compatibility Issue Detected**
              
              Thanks for reporting a compatibility issue! Here's how we can help resolve it:
              
              ## 🔍 First Steps:
              1. **Isolate the conflict** - Test with only VulkanMod + VulkanMod Extra + the conflicting mod
              2. **Check versions** - Ensure all mods support Minecraft 1.21.1
              3. **Review logs** - Look for specific error messages mentioning both mods
              
              ## 🛠️ Common Solutions:
              - **Rendering mods** (Sodium, Iris): VulkanMod replaces Sodium, conflicts are expected
              - **Optimization mods**: Some features may overlap, try disabling similar features in one mod
              - **GUI mods**: May interfere with VulkanMod's options screen integration
              
              ## 📋 Information Needed:
              - Exact mod versions causing the conflict
              - Whether this is a crash, visual glitch, or feature not working
              - Minimal mod list to reproduce the issue
              - Any error messages or crash logs
              
              We'll work with you to find a solution or workaround!`
            });`